"""add folders table and deck folder_id

Revision ID: 5081861ee069
Revises: e0d5c0ee6de8
Create Date: 2026-08-22 11:15:48.627467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5081861ee069'
down_revision: Union[str, Sequence[str], None] = 'e0d5c0ee6de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('en', 'ja', name='language', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_index('ix_folders_user_id_language', 'folders', ['user_id', 'language'], unique=False)
    op.add_column('decks', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_decks_folder_id'), 'decks', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'decks', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_index(op.f('ix_decks_folder_id'), table_name='decks')
    op.drop_column('decks', 'folder_id')
    op.drop_index('ix_folders_user_id_language', table_name='folders')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
