"""create user_card_progress table

Revision ID: 8610012c207a
Revises: f55965c4b0f8
Create Date: 2026-07-24 18:37:25.226655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8610012c207a'
down_revision: Union[str, Sequence[str], None] = 'f55965c4b0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_card_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_card')
    )
    op.create_index(op.f('ix_user_card_progress_card_id'), 'user_card_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_card_progress_next_review_date'), 'user_card_progress', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_user_card_progress_user_id'), 'user_card_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_card_progress_user_id'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_next_review_date'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_card_id'), table_name='user_card_progress')
    op.drop_table('user_card_progress')
    # ### end Alembic commands ###
