"""add user settings offer_pronunciation and new_cards_daily_limit

Revision ID: cadc829e7015
Revises: b7e2f5a91c04
Create Date: 2026-07-31 22:45:17.537190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cadc829e7015'
down_revision: Union[str, Sequence[str], None] = 'b7e2f5a91c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('offer_pronunciation', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('new_cards_daily_limit', sa.Integer(), server_default='20', nullable=False))
    op.create_check_constraint(
        'ck_user_new_cards_daily_limit_range',
        'users',
        'new_cards_daily_limit BETWEEN 1 AND 50',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_user_new_cards_daily_limit_range', 'users', type_='check')
    op.drop_column('users', 'new_cards_daily_limit')
    op.drop_column('users', 'offer_pronunciation')
    # ### end Alembic commands ###
