"""create pronunciation_attempts table

Revision ID: d6c55af8bef8
Revises: 38e5c18a5892
Create Date: 2026-07-26 14:11:57.928678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6c55af8bef8'
down_revision: Union[str, Sequence[str], None] = '38e5c18a5892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('transcript', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_attempts_card_id'), 'pronunciation_attempts', ['card_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_attempts_user_id'), 'pronunciation_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_attempts_user_id'), table_name='pronunciation_attempts')
    op.drop_index(op.f('ix_pronunciation_attempts_card_id'), table_name='pronunciation_attempts')
    op.drop_table('pronunciation_attempts')
    # ### end Alembic commands ###
