"""add user avatar_id

Revision ID: e0d5c0ee6de8
Revises: cadc829e7015
Create Date: 2026-08-11 17:40:20.143884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d5c0ee6de8'
down_revision: Union[str, Sequence[str], None] = 'cadc829e7015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', sa.Enum('sprout', 'leaf', 'pine', 'moon', 'stone', 'spirit', name='avatarid', native_enum=False), server_default='sprout', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
